Feature/flatwidget for consumption
OpenEMS/openems pull request #1472
Opened 2021-05-05 12:14 UTC by lukasrgr

2021-05-18 19:03 UTC, sfeilmeier requested changes

2021-05-18 19:03 UTC, sfeilmeier commented on ui/src/app/edge/live/flat/flat-widget-line/flat-widget-horizontal-line.html
> +</ng-template>
Das gefällt mir nicht besonders gut, weil diese Logik nicht aus dem Namen `flat-widget-horizontal-line` hervorgeht. Aber mir fällt auch nichts besseres ein, kann also so bleiben.

2021-05-19 07:11 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.ts
> +    this.edge.currentData.subscribe(currentData => {
ja hab ich eh in den Kommentar oben geschrieben. Hat früher aus einem mir nicht mehr bekannten Grund nicht funktioniert. Geht jetzt aber wieder. 

Also umgesetzt

2021-05-19 09:51 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.ts
> +      let channelValue = this.edge.currentData.value.channel[component.id + "/" + channel];
logik ist jetzt in onCurrentData(). Alte Logik ist entfernt, modal ist auch refactored

2021-05-19 09:52 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.ts
> +    this.edge.currentData.subscribe(currentData => {
ist entfernt

2021-05-19 09:52 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.ts
> +    this.consumptionMeterComponents = this.config.getComponentsImplementingNature("io.openems.edge.meter.api.SymmetricMeter").filter(component => component.properties['type'] == 'CONSUMPTION_METERED'
umgesetzt

2021-05-19 09:54 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.html
> +        <ng-container *ngIf="evcsComponents.length != 0 || consumptionMeterComponents.length != 0">
habe Kommentar geändert, aber ein if else ist in dem Sinne mit den Angular template directives nicht möglich

2021-05-19 09:54 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.html
> +        <ng-container *ngIf="evcsComponents.length > 0">
umgesetzt

2021-05-19 09:54 UTC, lukasrgr commented on ui/src/app/edge/live/common/consumption/consumption.component.html
> +                <ng-container *ngIf="evcsChargePower[component.id] > 0">
umgesetzt

2021-05-19 09:55 UTC, lukasrgr commented on ui/src/app/edge/live/flat/flat-widget-line/flat-widget-horizontal-line.html
> +</ng-template>
Ich bin auch nicht zufrieden damit, aber mir fällt auch nichts gutes und eindeutiges ein

2021-06-01 15:07 UTC, sfeilmeier approved these changes

2021-06-01 15:07 UTC, merged