Backend implementation for installation assistent
OpenEMS/openems pull request #1589
Opened 2021-08-09 11:46 UTC by mlang97

### Features
* Collect data (e.g. information about installer, configuration about the edge)
* Create setup protocol (PDF) from collected data
* Register customer and installer via login page 
![grafik](https://user-images.githubusercontent.com/35968713/128700553-a6488638-1b3b-45bd-9e5d-9d7a90149c97.png)
![grafik](https://user-images.githubusercontent.com/35968713/128700610-4d786acb-e310-4048-abc7-64d98a7dec0e.png)

2021-08-09 21:07 UTC, sfeilmeier requested changes
Some changes are required to comply with OpenEMS (instead of FEMS)

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.device";
Please revert to edge.device

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.device_status";
revert

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.openemsconfigupdate";
revert

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.device_user_role";
revert

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.setup_protocol";
edge

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.setup_protocol_production_lot";
edge

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/Field.java
> +		public static final String ODOO_MODEL = "fems.setup_protocol_item";
edge

2021-08-09 21:07 UTC, sfeilmeier commented on io.openems.backend.metadata.odoo/src/io/openems/backend/metadata/odoo/odoo/OdooHandler.java
> +			this.parent.logInfo(this.log, "Unable to find Edge by setupPassowrd [" + setupPassword + "]");
typo

2021-08-09 21:07 UTC, sfeilmeier commented on ui/src/app/index/index.component.html
> +                      href="https://portal.fenecon.de/web/reset_password?" style="text-decoration: none;">
to be removed

2021-08-09 21:07 UTC, sfeilmeier commented on ui/src/app/registration/modal/modal.component.html
> +                    <ion-checkbox slot="start" formControlName="subscribeNewsletter"></ion-checkbox>
FENECON specific; should be removed

2021-08-09 21:07 UTC, sfeilmeier commented on ui/src/app/shared/translate/de.ts
> +                acceptPrivacyPolicy: "Durch das Erstellen eines FENECON Accounts erkläre ich, die FENECON <a target=\"_blank\" href=\"https://fenecon.de/page/datenschutzerklaerung/\">Datenschutzerklä
remove

2021-08-11 06:57 UTC, mlang97 reviewed
All specified FEMS features are removed

2021-08-19 14:24 UTC, sfeilmeier approved these changes

2021-08-19 14:56 UTC, merged