New bundle for Alfen EVCS
OpenEMS/openems pull request #1944
Opened 2022-10-06 11:59 UTC by tsicking

2022-11-17 19:52 UTC, clehne commented on io.openems.edge.evcs.alfen/src/io/openems/edge/evcs/alfen/Alfen.java
> +	public enum ChannelId implements io.openems.edge.common.channel.ChannelId {
The EVCS interface has changed in the last couple of weeks. We need to check if this still compiles with the new interface

2022-11-17 19:56 UTC, clehne requested changes
see my comments

2022-11-17 19:56 UTC, clehne commented on io.openems.edge.evcs.alfen/src/io/openems/edge/evcs/alfen/AlfenImpl.java
> +		this._setMaximumHardwarePower(22000);
This values should be configurable. We should handle the configuration same as Keba implementation does - by using mA for min and max range of chargepoint. Note that this has to do with the UI Renault Zoe option, which reconfigures the chargepoint by setting a different min current (in mA)

2022-11-21 14:22 UTC, tsicking commented
The bundle needs to be updated to fit with the new Evcs interface. An adapted pull request will come soon.

2022-11-21 14:22 UTC, closed without merging