WIP: dezony integration
OpenEMS/openems pull request #2075
Opened 2023-02-23 16:48 UTC by hoip

2023-03-30 21:53 UTC, hoip commented
@mlang97 Can you please assign a review to the merge request?

2023-03-31 07:35 UTC, mlang97 commented
Thank you @hoip for your PR. @sebastianasen and me will have a look at this PR.

2023-04-03 08:49 UTC, sebastianasen requested changes
Thank you for implementing the charger!
Find my comments below.
Feel free to let us know how you continue with OpenEMS, or if you have any problems in production in the Community Forum.

2023-04-03 08:49 UTC, sebastianasen commented on io.openems.edge.evcs.dezony/src/io/openems/edge/evcs/dezony/Config.java
> +	@AttributeDefinition(name = "IP-Address", description = "The IP address of the charging station. If the charger has two connectors, the second/slave evcs has the IP 192.168.25.31.", required = true)
Please remove the description hint for the second evcs or adjust the IP to your needs / defaults.

2023-04-03 08:49 UTC, sebastianasen commented on io.openems.edge.evcs.dezony/src/io/openems/edge/evcs/dezony/Config.java
> +	@AttributeDefinition(name = "Port", description = "The IP address of the charging station. If the charger has two connectors, the second/slave evcs has the IP 192.168.25.31.", required = true)
Please adapt the description

2023-04-03 08:49 UTC, sebastianasen commented on io.openems.edge.evcs.dezony/src/io/openems/edge/evcs/dezony/DezonyApi.java
> +	    this.dezonyImpl._setChargingstationCommunicationFailed(true);
The value is not reset to false again when the connection is re-established.
Maybe you could do it like in the sendPostRequest method.

2023-04-03 08:52 UTC, sfeilmeier commented on io.openems.edge.evcs.dezony/.settings/org.eclipse.buildship.core.prefs
> +eclipse.preferences.version=1
Yes, please revert it to defaults - should work automatically with prepare-commit.sh

2023-04-03 16:31 UTC, hoip commented on io.openems.edge.evcs.dezony/src/io/openems/edge/evcs/dezony/DezonyImpl.java
> +	private final DezonyReadWorker readWorker = new DezonyReadWorker(this);
I am not quite sure in which order the parameters should be reordered, so I have already followed the production order of another integration.

2023-04-13 10:19 UTC, sebastianasen approved these changes
Thank you for adapting my change requests.
@sfeilmeier Decide if you want to take another look.
I think we could change this to a generic http worker #2100 later.

2023-04-14 12:19 UTC, sfeilmeier approved these changes
I left some comments and ToDos; some I fixed myself, others should be handled in future Pull Requests.

Thank you @hoip, @mlang97 and @sebastianasen, I really appreciate the patience, endurance and professionality that went into this Pull Request.

2023-04-14 12:20 UTC, merged