Siemens Logo as remote relay.
OpenEMS/openems pull request #2108
Opened 2023-03-17 10:50 UTC by DerWahreKlinki

Siemens Logo! as a network relay. Unconfigured Logo! starts with modbus registers 800+.
If configured you have to adjust either the modbus registers in Logo! or in OpenEMS

2023-03-27 08:32 UTC, hydroid7 commented
Thank you for the nice work. 
Can you please add device specific instructions / debug instructions to the readme file?
Best

2023-04-06 14:56 UTC, DerWahreKlinki commented
Hi,
sorry for the late answer. I´ve added a description to adoc and added a few features:
- now you can use different addresses for reading and writing. This could be necessary if you´ve defined some logic on the Logo
- I´ve made the offset-addresses configurable

2023-04-11 10:18 UTC, hydroid7 requested changes
Thank you for the changes, they LGTM.

Please run eclipse formatter and checkstyle again, as I spotted rule violations here and there.

2023-04-11 10:18 UTC, hydroid7 commented on io.openems.edge.io.siemenslogo/bnd.bnd
> +Bundle-Description: Siemens LOGO! 8 as network relais. Connected via Modbus. Relays starting \
Please remove the TODO from the description.

2023-04-12 13:16 UTC, DerWahreKlinki commented
done.
Hope, it´s OK now

2023-04-17 08:41 UTC, hydroid7 commented
Yes, `Config.java` seems to have a wrong package declaration.

2023-04-17 08:43 UTC, hydroid7 commented on io.openems.edge.io.siemenslogo/src/io/openems/edge/io/siemenslogo/Config.java
> +		name = "io.openems.edge.meter.EMH", //
Wrong package name.

2023-04-17 08:43 UTC, hydroid7 commented on io.openems.edge.io.siemenslogo/src/io/openems/edge/io/siemenslogo/Config.java
> +
Thats not a meter.

2023-04-17 10:56 UTC, DerWahreKlinki commented
That was the wrong config.java. I´m sorry for that.

I definetly have to improve my github-workflows.

But the build still fails. I`ll take a deeper look..

2023-04-17 11:21 UTC, hydroid7 commented
Almost done! :)
The messages are a lot of checkstyle violations.

You can run the checks with gradle:
```bash
$ ./gradlew :io.openems.edge.io.siemenslogo:checkstyleMain
```
That should be faster than pushing to github.

2023-04-17 12:27 UTC, DerWahreKlinki commented
Thanks for that advise! Now the build checks are on green light

2023-04-17 12:35 UTC, hydroid7 approved these changes

2023-04-17 12:36 UTC, hydroid7 commented
Thank you for that well documented module.

2023-09-06 13:25 UTC, closed without merging

2023-09-06 13:34 UTC, sfeilmeier commented
Sorry for taking so much time with reviews. I am now trying to distribute the task to different experienced OpenEMS software developers - but most of them are FENECON employees and there are also other tasks to do...

You don't have to close and reopen a PR. It's common practice to just do a "force push" on an existing branch. This also helps to keep the history of a PR.

2023-09-06 15:37 UTC, DerWahreKlinki commented
Don´t bother... I haven´t enough time to work on openems constantly either. 
You´ve told me before to "force push" a PR. Such things go out of the brain after a while...

Thanks for keeping up my requests!