Refactor streams to use toList() method
OpenEMS/openems pull request #2122
Opened 2023-03-28 09:22 UTC by SalmaElKhalfaoui

With Java 17 `.collect(Collectors.toList())` can be written as `.toList()`

2023-03-28 09:54 UTC, sfeilmeier commented
@michaelgrill: in App-Center you currently require modifiable lists. The new `toList()` method produces unmodifiable Lists and breaks JUnit tests. Do you want to refactor or should we keep the old Collectors where required?

2023-04-20 14:00 UTC, michaelgrill requested changes

2023-04-20 14:00 UTC, michaelgrill commented on io.openems.edge.core/src/io/openems/edge/core/appmanager/dependency/AppManagerAppHelperImpl.java
> +			var neededApps = this.getAllInstances().stream().filter(t -> t.appId.equals(appId)).collect(Collectors.toList());
you can also use `toList()` here or remove the change because its only formatting

2023-05-04 14:14 UTC, michaelgrill approved these changes
👍very good work

2023-05-04 15:09 UTC, sfeilmeier approved these changes

2023-05-04 15:10 UTC, merged