change contribution doc to describe "Eclipse [built in]" code formatter
OpenEMS/openems pull request #2271
Opened 2023-07-17 11:49 UTC by clehne

Current "Code Contribution Guidelines" documentation refer to the "Java" code formatter. The documentation should be switched to suggest the "Eclipse [built in]" code formatter.

Reason 1: Most of the code is already checked in with the  "Eclipse [built in]" code formatter.
Reason 2: the  "Eclipse [built in]" code formatter is the default code formatter when starting a new eclipse project. Less configuration lowers the barrier for newcomers to immediately start with programming.

2023-07-17 13:03 UTC, sfeilmeier requested changes
Thanks. One little typo.

2023-07-17 13:03 UTC, sfeilmeier commented on doc/modules/ROOT/pages/contribute/coding-guidelines.adoc
> +Use `Eclipse [built-in]` Code Formating Rules
_Formatting_ is with double 't'

2023-07-18 03:27 UTC, clehne commented on doc/modules/ROOT/pages/contribute/coding-guidelines.adoc
> +Use `Eclipse [built-in]` Code Formating Rules
Ups. Fixed.

2023-07-18 07:03 UTC, sfeilmeier approved these changes
Thanks!

2023-07-18 07:10 UTC, merged