UI: Removed unused channels subscription for the ToU widget.
OpenEMS/openems pull request #2352
Opened 2023-09-07 09:01 UTC by venu-sagar

->  Remove unused channels.
->  Made channels to subscribe based on factory id.

2023-09-07 09:47 UTC, lukasrgr requested changes

2023-09-07 09:47 UTC, lukasrgr commented on ui/src/app/edge/history/timeofusetariffdischarge/widget.component.ts
> +        }).then(() => {
chaining it 2 times is unecessary

2023-09-07 09:57 UTC, lukasrgr commented on ui/src/app/edge/history/timeofusetariffdischarge/widget.component.ts
> +        }).then(() => {
can it happen that no channels are sent with the promise at the end of the function?

2023-09-07 13:17 UTC, lukasrgr approved these changes

2023-09-08 09:57 UTC, sfeilmeier approved these changes
Ok 👍

@venu-sagar: Please remember, after merge+release of #2238 we have to drop the `DelayedTime`.

2023-09-08 09:58 UTC, merged

2023-09-08 10:36 UTC, venu-sagar commented
> Ok 👍
> 
> @venu-sagar: Please remember, after merge+release of #2238 we have to drop the `DelayedTime`.

We still need it. However, not based on the Factory ID, but based on the control mode selected.
So, control Mode 'CHARGE_CONSUMPTION' -> 'chargedTime', 'DELAY_DISCHARGE' -> 'delayedTime'