WIP: Edge: Introduce a http bridge
OpenEMS/openems pull request #2381
Opened 2023-10-06 07:30 UTC by sebastianasen

Introduce a new bridge for http connections and communication. 

Currently, each implementation of a device via RESTful APIs is implemented in its own bundle and is more or less stable depending on asynchronous calls.

In this PR it is currently used by the shelly IO plug as a first test. 

Co-authored-by: Michael Grill  <59126309+michaelgrill@users.noreply.github.com>

2023-12-19 13:12 UTC, sfeilmeier requested changes

2023-12-19 13:12 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplug/IoShellyPlugImpl.java
> +			this._setRelay(null);
The problem here is, that the 'Relay' Channel gets set properly, but you forgot `ActivePower` and `ActiveProductionEnergy`. This is a very typical mistake, but will lead to wrong data, e.g. in the UI.

My approach would be to use one common `BiConsumer` that handles the result and a exception. Also `processHttpResult` could then take both and act accordingly. This way you set all Channels in one place and it's more likely to not forget anything.

2024-01-11 13:51 UTC, michaelgrill commented on io.openems.edge.bridge.http/src/io/openems/edge/bridge/http/BridgeHttpImpl.java
> +			while (this.endpoints.peek().getCycleCount() == 0) {
i also prefer that way in general but what if the items `getCycleCount()` is not `0` then i would have to add it again

2024-01-11 13:53 UTC, michaelgrill commented on io.openems.edge.bridge.http/src/io/openems/edge/bridge/http/BridgeHttpImpl.java
> +			this.endpoints.forEach(EndpointCountdown::decreaseCycleCount);
no the loop is only to handle endpoints wich have hit `cycleCount` 0 before that i decrease every cycle

2024-01-16 08:20 UTC, sfeilmeier approved these changes

2024-01-16 08:21 UTC, merged

2024-02-06 05:08 UTC, Sn0w3y commented
```
2024-02-06T06:01:56,912 [tchQueue] ERROR [Events.Framework              ] FrameworkEvent ERROR
org.osgi.framework.ServiceException: Service factory returned null. (Component: IO.Shelly.Plus3EM (113))
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:385) ~[?:?]
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:249) ~[?:?]
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:362) ~[?:?]
	at org.apache.felix.framework.Felix.getService(Felix.java:3984) ~[?:?]
	at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:450) ~[?:?]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.obtain(EventHandlerProxy.java:296) ~[?:?]
	at org.apache.felix.eventadmin.impl.handler.EventHandlerProxy.sendEvent(EventHandlerProxy.java:424) ~[?:?]
	at org.apache.felix.eventadmin.impl.tasks.HandlerTask.runWithoutDenylistTiming(HandlerTask.java:82) ~[?:?]
	at org.apache.felix.eventadmin.impl.tasks.SyncDeliverTasks.execute(SyncDeliverTasks.java:107) ~[?:?]
	at org.apache.felix.eventadmin.impl.handler.EventAdminImpl.sendEvent(EventAdminImpl.java:155) ~[?:?]
	at org.apache.felix.eventadmin.impl.security.EventAdminSecurityDecorator.sendEvent(EventAdminSecurityDecorator.java:96) ~[?:?]
	at io.openems.common.event.EventBuilder.send(EventBuilder.java:68) ~[?:?]
	at io.openems.edge.core.cycle.CycleWorker.forever(CycleWorker.java:159) ~[?:?]
	at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:156) ~[?:?]
```
	
	
	Happens after one deactivates for example the Shelly Device