New modal-line element INPUT_UNIT
OpenEMS/openems pull request #2489
Opened 2024-01-17 09:06 UTC by JosefRick

Implements a new modal-line element INPUT_UNIT. It's the similar to INPUT with the option to change the unit with the following code line. 
eg: [control]="{type: 'INPUT_UNIT', properties: {unit: 'mA'}}">

2024-01-17 14:30 UTC, lukasrgr requested changes
this is a design error, i would add a optional unit to the control object and use "W" as fallback

2024-01-17 15:33 UTC, JosefRick commented
Yes, that is a better option. I have changed it now. Please take a look at it.

2024-01-18 16:06 UTC, lukasrgr requested changes
i think there is still a cleaner solution for this. Create a Enum e.g. InputUnits, that holds in this case only WATT = 'W'. Use this then as the type for the unit. Define the defaultValue in typescript then

2024-01-19 11:13 UTC, JosefRick commented
I'm not sure if this is really a clean solution, because for the control RANGE there is also the same way to define the unit if i understand it correct. So if we do it with Enum now, there are different possibilities for each control and so I think it is more difficult to understand which definition is the right one for each control. An alternative idea is, we make a new unit.ts in the shared folder so that every unit definition on the genericComponents can use it and it is defined for all at one point.

2024-02-02 13:09 UTC, lukasrgr commented
@JosefRick so you would define a fallback type "W" in this, do i understand correctly?

2024-02-02 17:04 UTC, JosefRick commented
@lukasrgr Yes, with this code I have defined a fallback 'W' if no properties are specified in the control type.
 For example _[control]="{type: 'INPUT', properties: {unit: 'mA'}}"_ in the modal.html will display the unit _mA_, and if no properties are specified, like this _[control]="{type: 'INPUT'}"_ the code will use _W_ as the unit.

2024-03-08 20:31 UTC, merged