Implement new Shelly Plus Plug S
OpenEMS/openems pull request #2529
Opened 2024-02-07 17:05 UTC by Sn0w3y

[Link](https://www.shelly.com/de/products/shop/shelly-plus-plug-s-1) to Product

The old one is likely not sold anymore, I guess.

2024-02-29 14:40 UTC, Sn0w3y commented
@michaelgrill maybe you can review this aswell ?

2024-04-28 19:31 UTC, sfeilmeier requested changes

2024-04-28 19:31 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplugs/IoShellyPlugsImpl.java
> +		this.calculateEnergy();
As you subscribe to two events, this method is called twice every Cycle - even if the Component is disabled.

2024-04-29 21:52 UTC, sfeilmeier approved these changes

2024-04-29 21:52 UTC, merged

2024-04-30 17:10 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplugs/Config.java
> +		name = "IO Shelly Plug S", //
thanks for the hint - overseen