Docker Workflow
OpenEMS/openems pull request #2568
Opened 2024-03-10 14:39 UTC by da-Kai

Build and Release Docker images on tag events.

continuation of #2358

2024-03-10 14:40 UTC, da-Kai commented
@sfeilmeier is there a OpenEMS Docker Hub account?

2024-03-10 16:56 UTC, sfeilmeier commented
> @sfeilmeier is there a OpenEMS Docker Hub account?

No, not yet. Feel free to create one.

2024-03-10 18:25 UTC, da-Kai commented
> No, not yet. Feel free to create one.

https://hub.docker.com/u/openems already exists :/

2024-03-11 08:27 UTC, sfeilmeier requested changes
Looks good. I still need somebody else to do a detailed review first. Maybe Manoj?

2024-03-13 07:43 UTC, manojniit commented
> Looks good. I still need somebody else to do a detailed review first. Maybe Manoj?


Everything is working properly. I checked it.

2024-03-14 15:02 UTC, sfeilmeier commented on tools/docker/openems-edge/config.d/Controller/Api/Backend/28628d01-a978-4328-9a8f-b9c7751ed2d2.config
Gitpod is using these files -> https://github.com/OpenEMS/openems/blob/develop/.gitpod.yml#L17

I did not test it, but this PR would (again) break Gitpod, right?

2024-03-14 22:25 UTC, sfeilmeier reviewed
Thank you!

Special acknowledgement for the ASCII-Art 😍🚀

2024-03-14 22:26 UTC, merged