Implement ShellyPlus1PM
OpenEMS/openems pull request #2571
Opened 2024-03-11 14:10 UTC by Sn0w3y

Example JSON:

`{"ble":{},"cloud":{"connected":true},"input:0":{"id":0,"state":false},"mqtt":{"connected":false},"switch:0":{"id":0, "source":"init", "output":false, "apower":0.0, "voltage":231.3, "current":0.000, "aenergy":{"total":8629.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1708858380},"temperature":{"tC":44.3, "tF":111.7}},"sys":{"mac":"80646FE34998","restart_required":false,"time":"11:53","unixtime":1708858386,"uptime":150390,"ram_size":260364,"ram_free":115308,"fs_size":458752,"fs_free":143360,"cfg_rev":22,"kvs_rev":2,"schedule_rev":0,"webhook_rev":0,"available_updates":{},"reset_reason":3},"wifi":{"sta_ip":"192.168.178.169","status":"got ip","ssid":"heizung","rssi":-48,"ap_client_count":0},"ws":{"connected":false}}`

2024-06-01 15:27 UTC, sfeilmeier requested changes
Bitte nochmal überarbeiten 👍

2024-06-01 15:27 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplus1pm/IoShellyPlus1PmImpl.java
> +		boolean relay0 = false;
Sollte `Boolean relay0 = null` sein.

2024-06-02 13:21 UTC, Sn0w3y commented
@sfeilmeier ist erledigt, danke für den Hinweis ! :)

2024-06-19 09:22 UTC, sfeilmeier approved these changes

2024-06-19 09:22 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplus1pm/IoShellyPlus1PmImpl.java
> +			this._setRelay(relay0);
This must be outside the brackets.

2024-06-19 09:22 UTC, sfeilmeier commented on io.openems.edge.io.shelly/test/io/openems/edge/io/shelly/shellyplus1pm/IoShellyPlus1PmImplTest.java
> +				.activate(MyConfig.create() //
Please provide full JUnit test, including parsing the JSON response

2024-06-19 09:22 UTC, merged