Refactored to use HttpBridge
OpenEMS/openems pull request #2573
Opened 2024-03-11 15:06 UTC by Sn0w3y

2024-03-31 21:38 UTC, sfeilmeier requested changes
Many topics appear over and over again in reviews. I believe we should eventually create an AbstractShelly class that combines all of the generic logic...

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25.java
> +	public default BooleanWriteChannel getRelay1OvertempChannel() {
The purpose of those methods is to allow easy access of channel values in (complicated) code. If you don't use them anywhere, it's not required to add them.

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25.java
> +		 * Indicates whether the associated meter is functioning properly.
Below its `is in Overtemp-State.` which sounds better suitable.

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +	protected void activate(ComponentContext context, Config config) {
Why `protected`?

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +		for (BooleanWriteChannel channel : this.digitalOutputChannels) {
Use `var` for more modern coding style

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +				valueText = valueOpt.get() ? "ON" : "OFF";
You did not mention this change in the PR description. We use the notion of `x`, `-` and `?` in many places in OpenEMS. Why change it here?

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +				} else if (i == 1) {
This logic assumes, that there `relays.size() == 2`. There are multiple ways to do it better, e.g. 
- `for (var i : new int[] { 0, 1 }) {`
- `for (int i = 0; i < 2; i++) {`
- add a `record` with relay, overtemp and overpower and call a static `parseRelay()` method twice

2024-03-31 21:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +		this.httpBridge.get(url).whenComplete((t, e) -> {
Should this not set `this._setSlaveCommunicationFailed(e != null);` like in the other Shelly implementations?

2024-04-01 14:09 UTC, Sn0w3y commented
@sfeilmeier do you think it makes sense to sum up the meter Values and set _setActivePower(summedUpValues) for this Shelly ?

2024-06-01 14:34 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +		this._setRelay1Overtemp(relay1State.overtemp());
This potentially produces a NullPointerException

2024-06-01 14:36 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
>  			this._setSlaveCommunicationFailed(false);
This is redundant/illogical

2024-06-01 14:38 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> +			for (int i = 0; i < 2; i++) {
This loop is not required

2024-06-01 14:42 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25.java
> +	public default BooleanWriteChannel getRelay2OverpowerChannel() {
This is not a WriteChannel.

2024-06-01 15:25 UTC, sfeilmeier approved these changes
Leider waren immer noch sehr viele Programmierfehler im Code. Ich muss die Qualitätsanforderungen hoch halten, deshalb kann ich das dann so nicht einfach mergen. So kommen wir mit den Shellys leider nur langsam voran. Von umfangreichen JUnit-Tests (z. B. parsing tests für die JSON-Response) spreche ich noch gar nicht.

Diesen PR habe ich jetzt nochmal selbst einigermaßen bereinigt. Bitte schau dir mal meine Commits und Kommentare an.

2024-06-01 15:30 UTC, merged