Implement a common eventExecuteWrite() for Shellys
OpenEMS/openems pull request #2658
Opened 2024-06-03 23:39 UTC by Sn0w3y

This PR centralizes the relay control functionality by introducing an enhanced executeWrite method within the Utils class of the io.openems.edge.io.shelly.common package. Previously, similar methods were implemented separately across various Shelly Components.

2024-06-04 22:01 UTC, sfeilmeier requested changes
I like the approach. Have some remarks, though.

2024-06-04 22:01 UTC, sfeilmeier commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/common/Utils.java
> +		httpBridge.get(url).whenComplete((t, e) -> {
This `CompletableFuture` should maybe be returned to handle error/success properly. Or you provide the `SlaveCommunicationFailed` channel directly to the `executeWrite` method so everything can be handled here.

2024-06-05 19:35 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/common/Utils.java
> +	@Reference(cardinality = ReferenceCardinality.MANDATORY)
Also not needed i guess, right ?
Removed !

2024-06-05 19:42 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/common/Utils.java
> +	public static String generateDebugLog(Channel<Boolean>[] relayChannels, Channel<Integer> activePowerChannel) {
Done ! We already talked about that recently somewhere i guess ! :)


I moved it to `io.openems.io.api` and renamed the Class to `ShellyUtils.java`

2024-06-10 19:55 UTC, Sn0w3y commented
@sfeilmeier could you do me a favour and resolve the Conflicts ? Otherwise i guess I need to open a new Branch with the Upstream Changes and Implement/Fix it again for the new Branch ?

2024-06-16 22:03 UTC, Sn0w3y commented
@sfeilmeier 

Test completed successfully :D I guess it was a Problem @github's Server

![image](https://github.com/OpenEMS/openems/assets/4571966/356922fc-faca-44b0-9dd5-f369cc61eee1)

2024-06-19 21:19 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly25/IoShelly25Impl.java
> -		try {
I had a NullPointerException whilst writing the Test - therefore we need to wrap this in a try catch.

2024-06-19 21:20 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shelly3em/IoShelly3EmImpl.java
> -	private void executeWrite() {
new API - can do rpc-channels

2024-06-19 21:20 UTC, Sn0w3y commented on io.openems.edge.io.shelly/src/io/openems/edge/io/shelly/shellyplusplugs/IoShellyPlusPlugsImpl.java
> -	private void executeWrite() {
new API Version can do rpc Channels

2024-07-04 16:11 UTC, Sn0w3y commented
@sfeilmeier maybe you can have a look  ? :)

2025-01-04 21:28 UTC, sfeilmeier approved these changes

2025-01-04 21:28 UTC, merged