WIP : Long short term memory prediction models for Time series Data
OpenEMS/openems pull request #2721
Opened 2024-07-26 11:32 UTC by Bishalghimire1997

This Model uses the LSTM (Type of Recurring neural network ) algorithm for predicting the Consumption and Production active power times series data.

2024-07-29 08:15 UTC, parapluplu commented
Very interesting and nice pull request! Do you have benchmarks values?

2024-09-30 09:28 UTC, pooran-c approved these changes
reviewed

2024-09-30 10:28 UTC, sfeilmeier requested changes

2024-09-30 10:28 UTC, sfeilmeier commented on io.openems.edge.predictor.api/src/io/openems/edge/predictor/api/prediction/Prediction.java
> +		return from(valueRange, buildMapDuoDecimus(time, values));
`Interval` is not checked here!

2024-09-30 10:28 UTC, sfeilmeier commented on io.openems.edge.predictor.api/src/io/openems/edge/predictor/api/prediction/Prediction.java
> +		return from(valueRange, buildMapDuoDecimus(time, values));
Need to discuss this "duodecimus" thing... it breaks a lot of assumptions (and Javadocs) if we suddenly have 5-minute predictions...

2024-12-05 10:37 UTC, sfeilmeier commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java
> +	 * you're a true computer scientist!
@Bishalghimire1997 🚀🤣

2024-12-05 11:30 UTC, sfeilmeier approved these changes
🚀

2024-12-05 11:36 UTC, sfeilmeier commented
@Bishalghimire1997 & @pooran-c: Thank you for your amazing work. This is definitely the most complete implementation of LSTM in Java out there. 🚀

I did some final touches here and there in the previous commits to fit with OpenEMS coding guidelines and best practices. Please check them out.

Some parts are still commented out and some others to be discussed and validated in production. I am still merging now to avoid having more merge conflicts in future. We can continue improving in `develop` from now on and I would also like to invite the (scientific) OpenEMS community to roll some tests. Or even better: I would welcome, if you could introduce the LSTM predictor to the OpenEMS Community on https://community.openems.io/. It was discussed briefly also on the OpenEMS Conference this year.

Some future TODOs here:
- Is it required to use ArrayLists or would a normal (immutable) list be sufficient? Then we could use simple `Stream.toList()` everywhere.
- I usually use `ZonedDateTime` instead of `OffsetDateTime`. Not sure which would fit better implications here...
- Reactivate or remove commented JUnit tests, remove System.out.println()s, etc.

2024-12-05 11:42 UTC, merged

2024-12-06 14:46 UTC, Bishalghimire1997 commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/interpolation/InterpolationManager.java
> +		// TODO why 96
That's Correct :)

2024-12-06 14:56 UTC, Bishalghimire1997 commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java
> +		return this.modelSeasonality.get(this.modelSeasonality.size() - 1);
To train the model, you need to ensure that the windowSizeSeasonality variable in the HyperParameters class (io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java) matches the amount of data available.
By default, windowSizeSeasonality is set to 7, which means you need at least 7 days of data with 15-minute intervals. If you have fewer days of data, try adjusting the windowSizeSeasonality variable to match the number of days available. However, using the default value of 7 is recommended for optimal performance.

Please let me know if this resolves the issue

2024-12-08 02:59 UTC, Bishalghimire1997 commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java
> +		return this.modelSeasonality.get(this.modelSeasonality.size() - 1);
To better investigate the error, I would appreciate additional details about the dataset. Could you please provide the following information?
	1.	Total Size of the Dataset: The number of samples or the file size.
	2.	Interval: The sampling interval or time step.

2024-12-10 07:24 UTC, Bishalghimire1997 commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java
> +		return this.modelSeasonality.get(this.modelSeasonality.size() - 1);
Thank you for the information. The algorithm is designed to train every 45th day, meaning it only considers the last 45 days of data during training.

I believe the issue lies in the batchSize variable in the HyperParameters class. This parameter determines how the dataset is divided into smaller batches for training, which helps reduce the system’s load. By default, the batchSize is set to 10, meaning the 45 days of data are divided into 10 batches. As a result, each training session effectively uses only 4.5 days’ worth of data.

To address this, I will fix the issue in the next pull request. For now, please navigate to the following path:

io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java

In the HyperParameters class, change the batchSize variable to 1 and let me know if this resolves the issue.

2024-12-10 16:47 UTC, Bishalghimire1997 commented on io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java
> +		return this.modelSeasonality.get(this.modelSeasonality.size() - 1);
Additionally, there is a file corresponding to the current channel ID in the ‘Model’ directory. Delete this file as well before starting the training process.

2025-01-21 09:52 UTC, yvesilknievil commented
Hello

I have tried to activate the LSTM predictor but it has been throwing me errors.

`Jan 21 10:40:58 raspberrypi java[34549]: =====> Average RMS error for  trend = 299.8913298466389
Jan 21 10:40:58 raspberrypi java[34549]: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.<init>(TrainAndValidateBatch.java:69)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.LstmTrain.run(LstmTrain.java:102)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.lang.Thread.run(Thread.java:1583)
Jan 21 10:40:58 raspberrypi java[34549]: Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.Objects.checkIndex(Objects.java:385)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.ArrayList.get(ArrayList.java:427)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.common.HyperParameters.getlastModelSeasonality(HyperParameters.java:800)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.MakeModel.trainSeasonality(MakeModel.java:117)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.lambda$new$0(TrainAndValidateBatch.java:53)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Jan 21 10:40:58 raspberrypi java[34549]: java.io.FileNotFoundException: /home/user/openems/data/lstm/UnmanagedConsumptionActivePower (No such file or directory)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.io.FileOutputStream.open0(Native Method)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:118)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.common.ReadAndSaveModels.save(ReadAndSaveModels.java:59)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.<init>(TrainAndValidateBatch.java:76)
Jan 21 10:40:58 raspberrypi java[34549]:         at io.openems.edge.predictor.lstm.train.LstmTrain.run(LstmTrain.java:102)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
Jan 21 10:40:58 raspberrypi java[34549]:         at java.base/java.lang.Thread.run(Thread.java:1583)
Jan 21 10:40:58 raspberrypi java[34549]: =====> Batch = 2/10
Jan 21 10:40:58 raspberrypi java[34549]: =====> Epoch=  0/10`


A few questions do rise:
I haven't built the code myself but used the jar file. I have declared the correct location of the data file in the service file (ubuntu).
Do you need to use rrd4j in order to feed the algorithm with data? I have all my data stored (from 2 years) in influx.

2025-01-21 11:01 UTC, pooran-c commented
@yvesilknievil Yes, you need to have rrd4j for the historical data.
Also, check if '...\openems\data\rrd4j\rrd4j0_sum' contains 'UnmanagedConsumptionActivePower'.

We’ll need to verify this before starting operations. We're working on handling this folder and its files to prompt errors early.

2025-01-22 16:36 UTC, yvesilknievil commented
Is there a way I can inject my influx data into this?
Transform them into rrdj4 compatible files?

2025-01-23 07:36 UTC, sfeilmeier commented
> Is there a way I can inject my influx data into this? Transform them into rrdj4 compatible files?

I did not look into the details, but the LSTM predictor uses a generic `Timedata` reference, so it should transparently work with InfluxDB out of the box.
```
	@Reference
	private Timedata timedata;
```
https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/PredictorLstmImpl.java#L75-L76

2025-01-23 07:48 UTC, yvesilknievil commented
thanks @sfeilmeier I'll have a look at this

However, even with rrd4 I get some weird errors that need debugging. I need to have a closer look but any help would be appreciated.

`Worker error. RuntimeException: Error in getting prediction execution - Caused by: java.util.NoSuchElementException
Jan 23 07:43:19 nuc01 java[6482]: java.lang.RuntimeException: Error in getting prediction execution
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.createNewPrediction(PredictorLstmImpl.java:162)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.api.prediction.AbstractPredictor.getPrediction(AbstractPredictor.java:68)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.core.predictormanager.PredictorManagerImpl.getPrediction(PredictorManagerImpl.java:94)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.UtilsV1.createSimulatorParams(UtilsV1.java:85)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.OptimizerV1.createParams(OptimizerV1.java:114)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.OptimizerV1.forever(OptimizerV1.java:62)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:155)
Jan 23 07:43:19 nuc01 java[6482]: Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.createNewPrediction(PredictorLstmImpl.java:147)
Jan 23 07:43:19 nuc01 java[6482]:         ... 6 more
Jan 23 07:43:19 nuc01 java[6482]: Caused by: java.util.NoSuchElementException
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1052)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.Collections.min(Collections.java:625)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.HyperParameters.getMinimumErrorModelSeasonality(HyperParameters.java:684)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.HyperParameters.getBestModelSeasonality(HyperParameters.java:766)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.LstmPredictor.predictSeasonality(LstmPredictor.java:42)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.predictSeasonality(PredictorLstmImpl.java:281)
Jan 23 07:43:19 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.lambda$createNewPrediction$0(PredictorLstmImpl.java:133)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
Jan 23 07:43:19 nuc01 java[6482]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Jan 23 07:43:19 nuc01 java[6482]: 2025-01-23T07:43:19,802 [1062-176] INFO  [edge.core.user.UserServiceImpl] Authentication successful with password only for user [Admin].
Jan 23 07:43:19 nuc01 java[6482]: 2025-01-23T07:43:19,804 [1062-176] INFO  [ontroller.api.common.ApiWorker] [ctrlApiRest0] Set [ess0/FeedPowerParaSet] to [10000] via API. Timeout is [60s]
Jan 23 07:43:19 nuc01 java[6482]: 2025-01-23T07:43:19,840 [_cycle  ] INFO  [ontroller.api.common.ApiWorker] [ctrlApiRest0] Set Channel [ess0/FeedPowerParaSet] to Value [10000]
Jan 23 07:43:19 nuc01 java[6482]: 2025-01-23T07:43:19,843 [_cycle  ] INFO  [ems.edge.ess.core.power.Solver] Currently active EQUALS constraints
Jan 23 07:43:19 nuc01 java[6482]: 2025-01-23T07:43:19,843 [_cycle  ] INFO  [ems.edge.ess.core.power.Solver] - Channel [SetActivePowerEquals]+ess0P EQUALS 147
Jan 23 07:43:20 nuc01 java[6482]: 2025-01-23T07:43:20,835 [_cycle  ] INFO  [ontroller.api.common.ApiWorker] [ctrlApiRest0] Set Channel [ess0/FeedPowerParaSet] to Value [10000]
Jan 23 07:43:20 nuc01 java[6482]: 2025-01-23T07:43:20,837 [_cycle  ] INFO  [ems.edge.ess.core.power.Solver] Currently active EQUALS constraints
Jan 23 07:43:20 nuc01 java[6482]: 2025-01-23T07:43:20,837 [_cycle  ] INFO  [ems.edge.ess.core.power.Solver] - Channel [SetActivePowerEquals]+ess0P EQUALS 742
Jan 23 07:43:21 nuc01 java[6482]: 2025-01-23T07:43:21,256 [_energy ] ERROR [s.common.worker.AbstractWorker] Worker error. RuntimeException: Error in getting prediction execution - Caused by: java.util.NoSuchElementException
Jan 23 07:43:21 nuc01 java[6482]: java.lang.RuntimeException: Error in getting prediction execution
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.createNewPrediction(PredictorLstmImpl.java:162)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.api.prediction.AbstractPredictor.getPrediction(AbstractPredictor.java:68)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.core.predictormanager.PredictorManagerImpl.getPrediction(PredictorManagerImpl.java:94)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.UtilsV1.createSimulatorParams(UtilsV1.java:85)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.OptimizerV1.createParams(OptimizerV1.java:114)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.energy.v1.optimizer.OptimizerV1.forever(OptimizerV1.java:62)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.common.worker.AbstractWorker$1.run(AbstractWorker.java:155)
Jan 23 07:43:21 nuc01 java[6482]: Caused by: java.util.concurrent.ExecutionException: java.util.NoSuchElementException
Jan 23 07:43:21 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
Jan 23 07:43:21 nuc01 java[6482]:         at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.createNewPrediction(PredictorLstmImpl.java:147)
Jan 23 07:43:21 nuc01 java[6482]:         ... 6 more
Jan 23 07:43:21 nuc01 java[6482]: Caused by: java.util.NoSuchElementException
Jan 23 07:43:21 nuc01 java[6482]:         at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1052)
Jan 23 07:43:21 nuc01 java[6482]:         at java.base/java.util.Collections.min(Collections.java:625)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.HyperParameters.getMinimumErrorModelSeasonality(HyperParameters.java:684)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.HyperParameters.getBestModelSeasonality(HyperParameters.java:766)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.common.LstmPredictor.predictSeasonality(LstmPredictor.java:42)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.predictSeasonality(PredictorLstmImpl.java:281)
Jan 23 07:43:21 nuc01 java[6482]:         at io.openems.edge.predictor.lstm.PredictorLstmImpl.lambda$createNewPrediction$0(PredictorLstmImpl.java:133)
Jan 23 0 [...]

2025-01-23 08:25 UTC, pooran-c commented
Hi @yvesilknievil , could you please share the data file if that's ok?

2025-01-23 09:25 UTC, yvesilknievil commented
@pooran-c sure
[UnmanagedConsumptionActivePower.zip](https://github.com/user-attachments/files/18518078/UnmanagedConsumptionActivePower.zip)

2025-01-23 14:57 UTC, Bishalghimire1997 commented
> Hello
> 
> I have tried to activate the LSTM predictor but it has been throwing me errors.
> 
> `Jan 21 10:40:58 raspberrypi java[34549]: =====> Average RMS error for trend = 299.8913298466389 Jan 21 10:40:58 raspberrypi java[34549]: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0 Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.<init>(TrainAndValidateBatch.java:69) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.LstmTrain.run(LstmTrain.java:102) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.lang.Thread.run(Thread.java:1583) Jan 21 10:40:58 raspberrypi java[34549]: Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0 Jan 21 10:40:58 raspberrypi java[34549]: at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.Objects.checkIndex(Objects.java:385) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.ArrayList.get(ArrayList.java:427) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.common.HyperParameters.getlastModelSeasonality(HyperParameters.java:800) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.MakeModel.trainSeasonality(MakeModel.java:117) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.lambda$new$0(TrainAndValidateBatch.java:53) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) Jan 21 10:40:58 raspberrypi java[34549]: java.io.FileNotFoundException: /home/user/openems/data/lstm/UnmanagedConsumptionActivePower (No such file or directory) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.io.FileOutputStream.open0(Native Method) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.io.FileOutputStream.open(FileOutputStream.java:289) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:230) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:118) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.io.FileWriter.<init>(FileWriter.java:67) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.common.ReadAndSaveModels.save(ReadAndSaveModels.java:59) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.TrainAndValidateBatch.<init>(TrainAndValidateBatch.java:76) Jan 21 10:40:58 raspberrypi java[34549]: at io.openems.edge.predictor.lstm.train.LstmTrain.run(LstmTrain.java:102) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) Jan 21 10:40:58 raspberrypi java[34549]: at java.base/java.lang.Thread.run(Thread.java:1583) Jan 21 10:40:58 raspberrypi java[34549]: =====> Batch = 2/10 Jan 21 10:40:58 raspberrypi java[34549]: =====> Epoch= 0/10`
> 
> A few questions do rise: I haven't built the code myself but used the jar file. I have declared the correct location of the data file in the service file (ubuntu). Do you need to use rrd4j in order to feed the algorithm with data? I have all my data stored (from 2 years) in influx.

Hi @yvesilknievil. 
I believe the issue lies in the batchSize variable within the HyperParameters class. This parameter determines how the dataset is divided into smaller batches for training, helping to manage the system’s load. Currently, the batchSize is set to 10 by default.

To address this, please navigate to the file located at io.openems.edge.predictor.lstm/src/io/openems/edge/predictor/lstm/common/HyperParameters.java and modify the batchSize variable to 1.
 Additionally, delete the file corresponding to the channel ID you are using for training from the ‘Model’ directory before starting the training process.
 Please let me know if it resolves the issue.

2025-01-23 19:31 UTC, yvesilknievil commented
That seems to have done the trick!

Thanks @Bishalghimire1997 and @pooran-c